<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol\MarketOrder;

use UnexpectedValueException;

/**
 * Protobuf type <code>protocol.MarketOrder.State</code>
 */
class State
{
    /**
     * Generated from protobuf enum <code>ACTIVE = 0;</code>
     */
    const ACTIVE = 0;
    /**
     * Generated from protobuf enum <code>INACTIVE = 1;</code>
     */
    const INACTIVE = 1;
    /**
     * Generated from protobuf enum <code>CANCELED = 2;</code>
     */
    const CANCELED = 2;

    private static $valueToName = [
        self::ACTIVE => 'ACTIVE',
        self::INACTIVE => 'INACTIVE',
        self::CANCELED => 'CANCELED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(State::class, \Protocol\MarketOrder_State::class);

