<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/contract/asset_issue_contract.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\AssetIssueContract\FrozenSupply instead.
     * @deprecated
     */
    class AssetIssueContract_FrozenSupply {}
}
class_exists(AssetIssueContract\FrozenSupply::class);
@trigger_error('Protocol\AssetIssueContract_FrozenSupply is deprecated and will be removed in the next major release. Use Protocol\AssetIssueContract\FrozenSupply instead', E_USER_DEPRECATED);

