<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/contract/storage_contract.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.BuyStorageBytesContract</code>
 */
class BuyStorageBytesContract extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes owner_address = 1;</code>
     */
    protected $owner_address = '';
    /**
     * storage bytes for buy
     *
     * Generated from protobuf field <code>int64 bytes = 2;</code>
     */
    protected $bytes = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $owner_address
     *     @type int|string $bytes
     *           storage bytes for buy
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Contract\StorageContract::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes owner_address = 1;</code>
     * @return string
     */
    public function getOwnerAddress()
    {
        return $this->owner_address;
    }

    /**
     * Generated from protobuf field <code>bytes owner_address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->owner_address = $var;

        return $this;
    }

    /**
     * storage bytes for buy
     *
     * Generated from protobuf field <code>int64 bytes = 2;</code>
     * @return int|string
     */
    public function getBytes()
    {
        return $this->bytes;
    }

    /**
     * storage bytes for buy
     *
     * Generated from protobuf field <code>int64 bytes = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBytes($var)
    {
        GPBUtil::checkInt64($var);
        $this->bytes = $var;

        return $this;
    }

}

