<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/contract/exchange_contract.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.ExchangeCreateContract</code>
 */
class ExchangeCreateContract extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes owner_address = 1;</code>
     */
    protected $owner_address = '';
    /**
     * Generated from protobuf field <code>bytes first_token_id = 2;</code>
     */
    protected $first_token_id = '';
    /**
     * Generated from protobuf field <code>int64 first_token_balance = 3;</code>
     */
    protected $first_token_balance = 0;
    /**
     * Generated from protobuf field <code>bytes second_token_id = 4;</code>
     */
    protected $second_token_id = '';
    /**
     * Generated from protobuf field <code>int64 second_token_balance = 5;</code>
     */
    protected $second_token_balance = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $owner_address
     *     @type string $first_token_id
     *     @type int|string $first_token_balance
     *     @type string $second_token_id
     *     @type int|string $second_token_balance
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Contract\ExchangeContract::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes owner_address = 1;</code>
     * @return string
     */
    public function getOwnerAddress()
    {
        return $this->owner_address;
    }

    /**
     * Generated from protobuf field <code>bytes owner_address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->owner_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes first_token_id = 2;</code>
     * @return string
     */
    public function getFirstTokenId()
    {
        return $this->first_token_id;
    }

    /**
     * Generated from protobuf field <code>bytes first_token_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFirstTokenId($var)
    {
        GPBUtil::checkString($var, False);
        $this->first_token_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 first_token_balance = 3;</code>
     * @return int|string
     */
    public function getFirstTokenBalance()
    {
        return $this->first_token_balance;
    }

    /**
     * Generated from protobuf field <code>int64 first_token_balance = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFirstTokenBalance($var)
    {
        GPBUtil::checkInt64($var);
        $this->first_token_balance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes second_token_id = 4;</code>
     * @return string
     */
    public function getSecondTokenId()
    {
        return $this->second_token_id;
    }

    /**
     * Generated from protobuf field <code>bytes second_token_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSecondTokenId($var)
    {
        GPBUtil::checkString($var, False);
        $this->second_token_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 second_token_balance = 5;</code>
     * @return int|string
     */
    public function getSecondTokenBalance()
    {
        return $this->second_token_balance;
    }

    /**
     * Generated from protobuf field <code>int64 second_token_balance = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSecondTokenBalance($var)
    {
        GPBUtil::checkInt64($var);
        $this->second_token_balance = $var;

        return $this;
    }

}

