<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/contract/smart_contract.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\SmartContract\ABI\Entry instead.
     * @deprecated
     */
    class SmartContract_ABI_Entry {}
}
class_exists(SmartContract\ABI\Entry::class);
@trigger_error('Protocol\SmartContract_ABI_Entry is deprecated and will be removed in the next major release. Use Protocol\SmartContract\ABI\Entry instead', E_USER_DEPRECATED);

