<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/contract/smart_contract.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\SmartContract\ABI\Entry\Param instead.
     * @deprecated
     */
    class SmartContract_ABI_Entry_Param {}
}
class_exists(SmartContract\ABI\Entry\Param::class);
@trigger_error('Protocol\SmartContract_ABI_Entry_Param is deprecated and will be removed in the next major release. Use Protocol\SmartContract\ABI\Entry\Param instead', E_USER_DEPRECATED);

