<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/contract/smart_contract.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\SmartContract\ABI instead.
     * @deprecated
     */
    class SmartContract_ABI {}
}
class_exists(SmartContract\ABI::class);
@trigger_error('Protocol\SmartContract_ABI is deprecated and will be removed in the next major release. Use Protocol\SmartContract\ABI instead', E_USER_DEPRECATED);

