<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/contract/smart_contract.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\SmartContract\ABI\Entry\StateMutabilityType instead.
     * @deprecated
     */
    class SmartContract_ABI_Entry_StateMutabilityType {}
}
class_exists(SmartContract\ABI\Entry\StateMutabilityType::class);
@trigger_error('Protocol\SmartContract_ABI_Entry_StateMutabilityType is deprecated and will be removed in the next major release. Use Protocol\SmartContract\ABI\Entry\StateMutabilityType instead', E_USER_DEPRECATED);

