<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/contract/balance_contract.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.UnfreezeBalanceContract</code>
 */
class UnfreezeBalanceContract extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes owner_address = 1;</code>
     */
    protected $owner_address = '';
    /**
     * Generated from protobuf field <code>.protocol.ResourceCode resource = 10;</code>
     */
    protected $resource = 0;
    /**
     * Generated from protobuf field <code>bytes receiver_address = 15;</code>
     */
    protected $receiver_address = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $owner_address
     *     @type int $resource
     *     @type string $receiver_address
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Contract\BalanceContract::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes owner_address = 1;</code>
     * @return string
     */
    public function getOwnerAddress()
    {
        return $this->owner_address;
    }

    /**
     * Generated from protobuf field <code>bytes owner_address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->owner_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protocol.ResourceCode resource = 10;</code>
     * @return int
     */
    public function getResource()
    {
        return $this->resource;
    }

    /**
     * Generated from protobuf field <code>.protocol.ResourceCode resource = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setResource($var)
    {
        GPBUtil::checkEnum($var, \Protocol\ResourceCode::class);
        $this->resource = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes receiver_address = 15;</code>
     * @return string
     */
    public function getReceiverAddress()
    {
        return $this->receiver_address;
    }

    /**
     * Generated from protobuf field <code>bytes receiver_address = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setReceiverAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->receiver_address = $var;

        return $this;
    }

}

