<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/contract/smart_contract.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.UpdateEnergyLimitContract</code>
 */
class UpdateEnergyLimitContract extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes owner_address = 1;</code>
     */
    protected $owner_address = '';
    /**
     * Generated from protobuf field <code>bytes contract_address = 2;</code>
     */
    protected $contract_address = '';
    /**
     * Generated from protobuf field <code>int64 origin_energy_limit = 3;</code>
     */
    protected $origin_energy_limit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $owner_address
     *     @type string $contract_address
     *     @type int|string $origin_energy_limit
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Contract\SmartContract::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes owner_address = 1;</code>
     * @return string
     */
    public function getOwnerAddress()
    {
        return $this->owner_address;
    }

    /**
     * Generated from protobuf field <code>bytes owner_address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->owner_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes contract_address = 2;</code>
     * @return string
     */
    public function getContractAddress()
    {
        return $this->contract_address;
    }

    /**
     * Generated from protobuf field <code>bytes contract_address = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContractAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->contract_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 origin_energy_limit = 3;</code>
     * @return int|string
     */
    public function getOriginEnergyLimit()
    {
        return $this->origin_energy_limit;
    }

    /**
     * Generated from protobuf field <code>int64 origin_energy_limit = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOriginEnergyLimit($var)
    {
        GPBUtil::checkInt64($var);
        $this->origin_energy_limit = $var;

        return $this;
    }

}

