<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/contract/vote_asset_contract.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.VoteAssetContract</code>
 */
class VoteAssetContract extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes owner_address = 1;</code>
     */
    protected $owner_address = '';
    /**
     * Generated from protobuf field <code>repeated bytes vote_address = 2;</code>
     */
    private $vote_address;
    /**
     * Generated from protobuf field <code>bool support = 3;</code>
     */
    protected $support = false;
    /**
     * Generated from protobuf field <code>int32 count = 5;</code>
     */
    protected $count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $owner_address
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $vote_address
     *     @type bool $support
     *     @type int $count
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Contract\VoteAssetContract::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes owner_address = 1;</code>
     * @return string
     */
    public function getOwnerAddress()
    {
        return $this->owner_address;
    }

    /**
     * Generated from protobuf field <code>bytes owner_address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->owner_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes vote_address = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVoteAddress()
    {
        return $this->vote_address;
    }

    /**
     * Generated from protobuf field <code>repeated bytes vote_address = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVoteAddress($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->vote_address = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool support = 3;</code>
     * @return bool
     */
    public function getSupport()
    {
        return $this->support;
    }

    /**
     * Generated from protobuf field <code>bool support = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setSupport($var)
    {
        GPBUtil::checkBool($var);
        $this->support = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 count = 5;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>int32 count = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->count = $var;

        return $this;
    }

}

