<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/contract/witness_contract.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.WitnessUpdateContract</code>
 */
class WitnessUpdateContract extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes owner_address = 1;</code>
     */
    protected $owner_address = '';
    /**
     * Generated from protobuf field <code>bytes update_url = 12;</code>
     */
    protected $update_url = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $owner_address
     *     @type string $update_url
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Contract\WitnessContract::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes owner_address = 1;</code>
     * @return string
     */
    public function getOwnerAddress()
    {
        return $this->owner_address;
    }

    /**
     * Generated from protobuf field <code>bytes owner_address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->owner_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes update_url = 12;</code>
     * @return string
     */
    public function getUpdateUrl()
    {
        return $this->update_url;
    }

    /**
     * Generated from protobuf field <code>bytes update_url = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdateUrl($var)
    {
        GPBUtil::checkString($var, False);
        $this->update_url = $var;

        return $this;
    }

}

