<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/contract/account_contract.proto

namespace GPBMetadata\Core\Contract;

class AccountContract
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Tron::initOnce();
        $pool->internalAddGeneratedFile(
            '
¤
$core/contract/account_contract.protoprotocol"l
AccountCreateContract
owner_address (
account_address (#
type (2.protocol.AccountType"D
AccountUpdateContract
account_name (
owner_address ("A
SetAccountIdContract

account_id (
owner_address ("«
AccountPermissionUpdateContract
owner_address (#
owner (2.protocol.Permission%
witness (2.protocol.Permission%
actives (2.protocol.PermissionBE
org.tron.protos.contractZ)github.com/tronprotocol/grpc-gateway/corebproto3'
        , true);

        static::$is_initialized = true;
    }
}

