<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/contract/witness_contract.proto

namespace GPBMetadata\Core\Contract;

class WitnessContract
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¥
$core/contract/witness_contract.protoprotocol";
WitnessCreateContract
owner_address (
url ("B
WitnessUpdateContract
owner_address (

update_url ("¢
VoteWitnessContract
owner_address (1
votes (2".protocol.VoteWitnessContract.Vote
support (0
Vote
vote_address (

vote_count (BE
org.tron.protos.contractZ)github.com/tronprotocol/grpc-gateway/corebproto3'
        , true);

        static::$is_initialized = true;
    }
}

