<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/contract/smart_contract.proto

namespace Protocol\SmartContract\ABI;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.SmartContract.ABI.Entry</code>
 */
class Entry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool anonymous = 1;</code>
     */
    protected $anonymous = false;
    /**
     * Generated from protobuf field <code>bool constant = 2;</code>
     */
    protected $constant = false;
    /**
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>repeated .protocol.SmartContract.ABI.Entry.Param inputs = 4;</code>
     */
    private $inputs;
    /**
     * Generated from protobuf field <code>repeated .protocol.SmartContract.ABI.Entry.Param outputs = 5;</code>
     */
    private $outputs;
    /**
     * Generated from protobuf field <code>.protocol.SmartContract.ABI.Entry.EntryType type = 6;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>bool payable = 7;</code>
     */
    protected $payable = false;
    /**
     * Generated from protobuf field <code>.protocol.SmartContract.ABI.Entry.StateMutabilityType stateMutability = 8;</code>
     */
    protected $stateMutability = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $anonymous
     *     @type bool $constant
     *     @type string $name
     *     @type \Protocol\SmartContract\ABI\Entry\Param[]|\Google\Protobuf\Internal\RepeatedField $inputs
     *     @type \Protocol\SmartContract\ABI\Entry\Param[]|\Google\Protobuf\Internal\RepeatedField $outputs
     *     @type int $type
     *     @type bool $payable
     *     @type int $stateMutability
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Contract\SmartContract::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool anonymous = 1;</code>
     * @return bool
     */
    public function getAnonymous()
    {
        return $this->anonymous;
    }

    /**
     * Generated from protobuf field <code>bool anonymous = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setAnonymous($var)
    {
        GPBUtil::checkBool($var);
        $this->anonymous = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool constant = 2;</code>
     * @return bool
     */
    public function getConstant()
    {
        return $this->constant;
    }

    /**
     * Generated from protobuf field <code>bool constant = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setConstant($var)
    {
        GPBUtil::checkBool($var);
        $this->constant = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.SmartContract.ABI.Entry.Param inputs = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInputs()
    {
        return $this->inputs;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.SmartContract.ABI.Entry.Param inputs = 4;</code>
     * @param \Protocol\SmartContract\ABI\Entry\Param[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInputs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protocol\SmartContract\ABI\Entry\Param::class);
        $this->inputs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.SmartContract.ABI.Entry.Param outputs = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOutputs()
    {
        return $this->outputs;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.SmartContract.ABI.Entry.Param outputs = 5;</code>
     * @param \Protocol\SmartContract\ABI\Entry\Param[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOutputs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protocol\SmartContract\ABI\Entry\Param::class);
        $this->outputs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protocol.SmartContract.ABI.Entry.EntryType type = 6;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.protocol.SmartContract.ABI.Entry.EntryType type = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Protocol\SmartContract\ABI\Entry\EntryType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool payable = 7;</code>
     * @return bool
     */
    public function getPayable()
    {
        return $this->payable;
    }

    /**
     * Generated from protobuf field <code>bool payable = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setPayable($var)
    {
        GPBUtil::checkBool($var);
        $this->payable = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protocol.SmartContract.ABI.Entry.StateMutabilityType stateMutability = 8;</code>
     * @return int
     */
    public function getStateMutability()
    {
        return $this->stateMutability;
    }

    /**
     * Generated from protobuf field <code>.protocol.SmartContract.ABI.Entry.StateMutabilityType stateMutability = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setStateMutability($var)
    {
        GPBUtil::checkEnum($var, \Protocol\SmartContract\ABI\Entry\StateMutabilityType::class);
        $this->stateMutability = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Entry::class, \Protocol\SmartContract_ABI_Entry::class);

