<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/contract/smart_contract.proto

namespace Protocol\SmartContract\ABI\Entry;

use UnexpectedValueException;

/**
 * Protobuf type <code>protocol.SmartContract.ABI.Entry.StateMutabilityType</code>
 */
class StateMutabilityType
{
    /**
     * Generated from protobuf enum <code>UnknownMutabilityType = 0;</code>
     */
    const UnknownMutabilityType = 0;
    /**
     * Generated from protobuf enum <code>Pure = 1;</code>
     */
    const Pure = 1;
    /**
     * Generated from protobuf enum <code>View = 2;</code>
     */
    const View = 2;
    /**
     * Generated from protobuf enum <code>Nonpayable = 3;</code>
     */
    const Nonpayable = 3;
    /**
     * Generated from protobuf enum <code>Payable = 4;</code>
     */
    const Payable = 4;

    private static $valueToName = [
        self::UnknownMutabilityType => 'UnknownMutabilityType',
        self::Pure => 'Pure',
        self::View => 'View',
        self::Nonpayable => 'Nonpayable',
        self::Payable => 'Payable',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(StateMutabilityType::class, \Protocol\SmartContract_ABI_Entry_StateMutabilityType::class);

