<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/contract/smart_contract.proto

namespace Protocol\SmartContract;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.SmartContract.ABI</code>
 */
class ABI extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .protocol.SmartContract.ABI.Entry entrys = 1;</code>
     */
    private $entrys;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Protocol\SmartContract\ABI\Entry[]|\Google\Protobuf\Internal\RepeatedField $entrys
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Contract\SmartContract::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.SmartContract.ABI.Entry entrys = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEntrys()
    {
        return $this->entrys;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.SmartContract.ABI.Entry entrys = 1;</code>
     * @param \Protocol\SmartContract\ABI\Entry[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEntrys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protocol\SmartContract\ABI\Entry::class);
        $this->entrys = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ABI::class, \Protocol\SmartContract_ABI::class);

