<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\Account\AccountResource instead.
     * @deprecated
     */
    class Account_AccountResource {}
}
class_exists(Account\AccountResource::class);
@trigger_error('Protocol\Account_AccountResource is deprecated and will be removed in the next major release. Use Protocol\Account\AccountResource instead', E_USER_DEPRECATED);

