<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\Account\Frozen instead.
     * @deprecated
     */
    class Account_Frozen {}
}
class_exists(Account\Frozen::class);
@trigger_error('Protocol\Account_Frozen is deprecated and will be removed in the next major release. Use Protocol\Account\Frozen instead', E_USER_DEPRECATED);

