<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.authority</code>
 */
class authority extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protocol.AccountId account = 1;</code>
     */
    protected $account = null;
    /**
     * Generated from protobuf field <code>bytes permission_name = 2;</code>
     */
    protected $permission_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Protocol\AccountId $account
     *     @type string $permission_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Tron::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protocol.AccountId account = 1;</code>
     * @return \Protocol\AccountId
     */
    public function getAccount()
    {
        return isset($this->account) ? $this->account : null;
    }

    public function hasAccount()
    {
        return isset($this->account);
    }

    public function clearAccount()
    {
        unset($this->account);
    }

    /**
     * Generated from protobuf field <code>.protocol.AccountId account = 1;</code>
     * @param \Protocol\AccountId $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkMessage($var, \Protocol\AccountId::class);
        $this->account = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes permission_name = 2;</code>
     * @return string
     */
    public function getPermissionName()
    {
        return $this->permission_name;
    }

    /**
     * Generated from protobuf field <code>bytes permission_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPermissionName($var)
    {
        GPBUtil::checkString($var, False);
        $this->permission_name = $var;

        return $this;
    }

}

