<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Discover.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.BackupMessage</code>
 */
class BackupMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool flag = 1;</code>
     */
    protected $flag = false;
    /**
     * Generated from protobuf field <code>int32 priority = 2;</code>
     */
    protected $priority = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $flag
     *     @type int $priority
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Discover::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool flag = 1;</code>
     * @return bool
     */
    public function getFlag()
    {
        return $this->flag;
    }

    /**
     * Generated from protobuf field <code>bool flag = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setFlag($var)
    {
        GPBUtil::checkBool($var);
        $this->flag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 priority = 2;</code>
     * @return int
     */
    public function getPriority()
    {
        return $this->priority;
    }

    /**
     * Generated from protobuf field <code>int32 priority = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPriority($var)
    {
        GPBUtil::checkInt32($var);
        $this->priority = $var;

        return $this;
    }

}

