<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\BlockInventory\BlockId instead.
     * @deprecated
     */
    class BlockInventory_BlockId {}
}
class_exists(BlockInventory\BlockId::class);
@trigger_error('Protocol\BlockInventory_BlockId is deprecated and will be removed in the next major release. Use Protocol\BlockInventory\BlockId instead', E_USER_DEPRECATED);

