<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.ChainParameters</code>
 */
class ChainParameters extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .protocol.ChainParameters.ChainParameter chainParameter = 1;</code>
     */
    private $chainParameter;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Protocol\ChainParameters\ChainParameter[]|\Google\Protobuf\Internal\RepeatedField $chainParameter
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Tron::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.ChainParameters.ChainParameter chainParameter = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChainParameter()
    {
        return $this->chainParameter;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.ChainParameters.ChainParameter chainParameter = 1;</code>
     * @param \Protocol\ChainParameters\ChainParameter[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChainParameter($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protocol\ChainParameters\ChainParameter::class);
        $this->chainParameter = $arr;

        return $this;
    }

}

