<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\ChainInventory\BlockId instead.
     * @deprecated
     */
    class ChainInventory_BlockId {}
}
class_exists(ChainInventory\BlockId::class);
@trigger_error('Protocol\ChainInventory_BlockId is deprecated and will be removed in the next major release. Use Protocol\ChainInventory\BlockId instead', E_USER_DEPRECATED);

