<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.HelloMessage</code>
 */
class HelloMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protocol.Endpoint from = 1;</code>
     */
    protected $from = null;
    /**
     * Generated from protobuf field <code>int32 version = 2;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>int64 timestamp = 3;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>.protocol.HelloMessage.BlockId genesisBlockId = 4;</code>
     */
    protected $genesisBlockId = null;
    /**
     * Generated from protobuf field <code>.protocol.HelloMessage.BlockId solidBlockId = 5;</code>
     */
    protected $solidBlockId = null;
    /**
     * Generated from protobuf field <code>.protocol.HelloMessage.BlockId headBlockId = 6;</code>
     */
    protected $headBlockId = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Protocol\Endpoint $from
     *     @type int $version
     *     @type int|string $timestamp
     *     @type \Protocol\HelloMessage\BlockId $genesisBlockId
     *     @type \Protocol\HelloMessage\BlockId $solidBlockId
     *     @type \Protocol\HelloMessage\BlockId $headBlockId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Tron::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protocol.Endpoint from = 1;</code>
     * @return \Protocol\Endpoint
     */
    public function getFrom()
    {
        return isset($this->from) ? $this->from : null;
    }

    public function hasFrom()
    {
        return isset($this->from);
    }

    public function clearFrom()
    {
        unset($this->from);
    }

    /**
     * Generated from protobuf field <code>.protocol.Endpoint from = 1;</code>
     * @param \Protocol\Endpoint $var
     * @return $this
     */
    public function setFrom($var)
    {
        GPBUtil::checkMessage($var, \Protocol\Endpoint::class);
        $this->from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 version = 2;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>int32 version = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 3;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protocol.HelloMessage.BlockId genesisBlockId = 4;</code>
     * @return \Protocol\HelloMessage\BlockId
     */
    public function getGenesisBlockId()
    {
        return isset($this->genesisBlockId) ? $this->genesisBlockId : null;
    }

    public function hasGenesisBlockId()
    {
        return isset($this->genesisBlockId);
    }

    public function clearGenesisBlockId()
    {
        unset($this->genesisBlockId);
    }

    /**
     * Generated from protobuf field <code>.protocol.HelloMessage.BlockId genesisBlockId = 4;</code>
     * @param \Protocol\HelloMessage\BlockId $var
     * @return $this
     */
    public function setGenesisBlockId($var)
    {
        GPBUtil::checkMessage($var, \Protocol\HelloMessage\BlockId::class);
        $this->genesisBlockId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protocol.HelloMessage.BlockId solidBlockId = 5;</code>
     * @return \Protocol\HelloMessage\BlockId
     */
    public function getSolidBlockId()
    {
        return isset($this->solidBlockId) ? $this->solidBlockId : null;
    }

    public function hasSolidBlockId()
    {
        return isset($this->solidBlockId);
    }

    public function clearSolidBlockId()
    {
        unset($this->solidBlockId);
    }

    /**
     * Generated from protobuf field <code>.protocol.HelloMessage.BlockId solidBlockId = 5;</code>
     * @param \Protocol\HelloMessage\BlockId $var
     * @return $this
     */
    public function setSolidBlockId($var)
    {
        GPBUtil::checkMessage($var, \Protocol\HelloMessage\BlockId::class);
        $this->solidBlockId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protocol.HelloMessage.BlockId headBlockId = 6;</code>
     * @return \Protocol\HelloMessage\BlockId
     */
    public function getHeadBlockId()
    {
        return isset($this->headBlockId) ? $this->headBlockId : null;
    }

    public function hasHeadBlockId()
    {
        return isset($this->headBlockId);
    }

    public function clearHeadBlockId()
    {
        unset($this->headBlockId);
    }

    /**
     * Generated from protobuf field <code>.protocol.HelloMessage.BlockId headBlockId = 6;</code>
     * @param \Protocol\HelloMessage\BlockId $var
     * @return $this
     */
    public function setHeadBlockId($var)
    {
        GPBUtil::checkMessage($var, \Protocol\HelloMessage\BlockId::class);
        $this->headBlockId = $var;

        return $this;
    }

}

