<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\InternalTransaction\CallValueInfo instead.
     * @deprecated
     */
    class InternalTransaction_CallValueInfo {}
}
class_exists(InternalTransaction\CallValueInfo::class);
@trigger_error('Protocol\InternalTransaction_CallValueInfo is deprecated and will be removed in the next major release. Use Protocol\InternalTransaction\CallValueInfo instead', E_USER_DEPRECATED);

