<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.MarketPrice</code>
 */
class MarketPrice extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 sell_token_quantity = 1;</code>
     */
    protected $sell_token_quantity = 0;
    /**
     * Generated from protobuf field <code>int64 buy_token_quantity = 2;</code>
     */
    protected $buy_token_quantity = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $sell_token_quantity
     *     @type int|string $buy_token_quantity
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Tron::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 sell_token_quantity = 1;</code>
     * @return int|string
     */
    public function getSellTokenQuantity()
    {
        return $this->sell_token_quantity;
    }

    /**
     * Generated from protobuf field <code>int64 sell_token_quantity = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSellTokenQuantity($var)
    {
        GPBUtil::checkInt64($var);
        $this->sell_token_quantity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 buy_token_quantity = 2;</code>
     * @return int|string
     */
    public function getBuyTokenQuantity()
    {
        return $this->buy_token_quantity;
    }

    /**
     * Generated from protobuf field <code>int64 buy_token_quantity = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBuyTokenQuantity($var)
    {
        GPBUtil::checkInt64($var);
        $this->buy_token_quantity = $var;

        return $this;
    }

}

