<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.MarketOrderDetail</code>
 */
class MarketOrderDetail extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes makerOrderId = 1;</code>
     */
    protected $makerOrderId = '';
    /**
     * Generated from protobuf field <code>bytes takerOrderId = 2;</code>
     */
    protected $takerOrderId = '';
    /**
     * Generated from protobuf field <code>int64 fillSellQuantity = 3;</code>
     */
    protected $fillSellQuantity = 0;
    /**
     * Generated from protobuf field <code>int64 fillBuyQuantity = 4;</code>
     */
    protected $fillBuyQuantity = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $makerOrderId
     *     @type string $takerOrderId
     *     @type int|string $fillSellQuantity
     *     @type int|string $fillBuyQuantity
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Tron::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes makerOrderId = 1;</code>
     * @return string
     */
    public function getMakerOrderId()
    {
        return $this->makerOrderId;
    }

    /**
     * Generated from protobuf field <code>bytes makerOrderId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMakerOrderId($var)
    {
        GPBUtil::checkString($var, False);
        $this->makerOrderId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes takerOrderId = 2;</code>
     * @return string
     */
    public function getTakerOrderId()
    {
        return $this->takerOrderId;
    }

    /**
     * Generated from protobuf field <code>bytes takerOrderId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTakerOrderId($var)
    {
        GPBUtil::checkString($var, False);
        $this->takerOrderId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 fillSellQuantity = 3;</code>
     * @return int|string
     */
    public function getFillSellQuantity()
    {
        return $this->fillSellQuantity;
    }

    /**
     * Generated from protobuf field <code>int64 fillSellQuantity = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFillSellQuantity($var)
    {
        GPBUtil::checkInt64($var);
        $this->fillSellQuantity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 fillBuyQuantity = 4;</code>
     * @return int|string
     */
    public function getFillBuyQuantity()
    {
        return $this->fillBuyQuantity;
    }

    /**
     * Generated from protobuf field <code>int64 fillBuyQuantity = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFillBuyQuantity($var)
    {
        GPBUtil::checkInt64($var);
        $this->fillBuyQuantity = $var;

        return $this;
    }

}

