<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.MarketOrderIdList</code>
 */
class MarketOrderIdList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes head = 1;</code>
     */
    protected $head = '';
    /**
     * Generated from protobuf field <code>bytes tail = 2;</code>
     */
    protected $tail = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $head
     *     @type string $tail
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Tron::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes head = 1;</code>
     * @return string
     */
    public function getHead()
    {
        return $this->head;
    }

    /**
     * Generated from protobuf field <code>bytes head = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHead($var)
    {
        GPBUtil::checkString($var, False);
        $this->head = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes tail = 2;</code>
     * @return string
     */
    public function getTail()
    {
        return $this->tail;
    }

    /**
     * Generated from protobuf field <code>bytes tail = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTail($var)
    {
        GPBUtil::checkString($var, False);
        $this->tail = $var;

        return $this;
    }

}

