<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\MarketOrder\State instead.
     * @deprecated
     */
    class MarketOrder_State {}
}
class_exists(MarketOrder\State::class);
@trigger_error('Protocol\MarketOrder_State is deprecated and will be removed in the next major release. Use Protocol\MarketOrder\State instead', E_USER_DEPRECATED);

