<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.MarketOrderPairList</code>
 */
class MarketOrderPairList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .protocol.MarketOrderPair orderPair = 1;</code>
     */
    private $orderPair;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Protocol\MarketOrderPair[]|\Google\Protobuf\Internal\RepeatedField $orderPair
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Tron::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.MarketOrderPair orderPair = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrderPair()
    {
        return $this->orderPair;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.MarketOrderPair orderPair = 1;</code>
     * @param \Protocol\MarketOrderPair[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrderPair($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protocol\MarketOrderPair::class);
        $this->orderPair = $arr;

        return $this;
    }

}

