<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.MarketOrderPair</code>
 */
class MarketOrderPair extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes sell_token_id = 1;</code>
     */
    protected $sell_token_id = '';
    /**
     * Generated from protobuf field <code>bytes buy_token_id = 2;</code>
     */
    protected $buy_token_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sell_token_id
     *     @type string $buy_token_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Tron::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes sell_token_id = 1;</code>
     * @return string
     */
    public function getSellTokenId()
    {
        return $this->sell_token_id;
    }

    /**
     * Generated from protobuf field <code>bytes sell_token_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSellTokenId($var)
    {
        GPBUtil::checkString($var, False);
        $this->sell_token_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes buy_token_id = 2;</code>
     * @return string
     */
    public function getBuyTokenId()
    {
        return $this->buy_token_id;
    }

    /**
     * Generated from protobuf field <code>bytes buy_token_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBuyTokenId($var)
    {
        GPBUtil::checkString($var, False);
        $this->buy_token_id = $var;

        return $this;
    }

}

