<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\NodeInfo\ConfigNodeInfo instead.
     * @deprecated
     */
    class NodeInfo_ConfigNodeInfo {}
}
class_exists(NodeInfo\ConfigNodeInfo::class);
@trigger_error('Protocol\NodeInfo_ConfigNodeInfo is deprecated and will be removed in the next major release. Use Protocol\NodeInfo\ConfigNodeInfo instead', E_USER_DEPRECATED);

