<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\NodeInfo\MachineInfo\DeadLockThreadInfo instead.
     * @deprecated
     */
    class NodeInfo_MachineInfo_DeadLockThreadInfo {}
}
class_exists(NodeInfo\MachineInfo\DeadLockThreadInfo::class);
@trigger_error('Protocol\NodeInfo_MachineInfo_DeadLockThreadInfo is deprecated and will be removed in the next major release. Use Protocol\NodeInfo\MachineInfo\DeadLockThreadInfo instead', E_USER_DEPRECATED);

