<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\NodeInfo\MachineInfo instead.
     * @deprecated
     */
    class NodeInfo_MachineInfo {}
}
class_exists(NodeInfo\MachineInfo::class);
@trigger_error('Protocol\NodeInfo_MachineInfo is deprecated and will be removed in the next major release. Use Protocol\NodeInfo\MachineInfo instead', E_USER_DEPRECATED);

