<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\Transaction\Contract\ContractType instead.
     * @deprecated
     */
    class Transaction_Contract_ContractType {}
}
class_exists(Transaction\Contract\ContractType::class);
@trigger_error('Protocol\Transaction_Contract_ContractType is deprecated and will be removed in the next major release. Use Protocol\Transaction\Contract\ContractType instead', E_USER_DEPRECATED);

