<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.Transaction</code>
 */
class Transaction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protocol.Transaction.raw raw_data = 1;</code>
     */
    protected $raw_data = null;
    /**
     * only support size = 1, repeated list here for muti-sig extension
     *
     * Generated from protobuf field <code>repeated bytes signature = 2;</code>
     */
    private $signature;
    /**
     * Generated from protobuf field <code>repeated .protocol.Transaction.Result ret = 5;</code>
     */
    private $ret;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Protocol\Transaction\raw $raw_data
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $signature
     *           only support size = 1, repeated list here for muti-sig extension
     *     @type \Protocol\Transaction\Result[]|\Google\Protobuf\Internal\RepeatedField $ret
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Tron::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protocol.Transaction.raw raw_data = 1;</code>
     * @return \Protocol\Transaction\raw
     */
    public function getRawData()
    {
        return isset($this->raw_data) ? $this->raw_data : null;
    }

    public function hasRawData()
    {
        return isset($this->raw_data);
    }

    public function clearRawData()
    {
        unset($this->raw_data);
    }

    /**
     * Generated from protobuf field <code>.protocol.Transaction.raw raw_data = 1;</code>
     * @param \Protocol\Transaction\raw $var
     * @return $this
     */
    public function setRawData($var)
    {
        GPBUtil::checkMessage($var, \Protocol\Transaction\raw::class);
        $this->raw_data = $var;

        return $this;
    }

    /**
     * only support size = 1, repeated list here for muti-sig extension
     *
     * Generated from protobuf field <code>repeated bytes signature = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * only support size = 1, repeated list here for muti-sig extension
     *
     * Generated from protobuf field <code>repeated bytes signature = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSignature($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->signature = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.Transaction.Result ret = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRet()
    {
        return $this->ret;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.Transaction.Result ret = 5;</code>
     * @param \Protocol\Transaction\Result[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRet($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protocol\Transaction\Result::class);
        $this->ret = $arr;

        return $this;
    }

}

