<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\Transaction\raw instead.
     * @deprecated
     */
    class Transaction_raw {}
}
class_exists(Transaction\raw::class);
@trigger_error('Protocol\Transaction_raw is deprecated and will be removed in the next major release. Use Protocol\Transaction\raw instead', E_USER_DEPRECATED);

