<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\TransactionInfo\Log instead.
     * @deprecated
     */
    class TransactionInfo_Log {}
}
class_exists(TransactionInfo\Log::class);
@trigger_error('Protocol\TransactionInfo_Log is deprecated and will be removed in the next major release. Use Protocol\TransactionInfo\Log instead', E_USER_DEPRECATED);

