<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\Transaction\Contract instead.
     * @deprecated
     */
    class Transaction_Contract {}
}
class_exists(Transaction\Contract::class);
@trigger_error('Protocol\Transaction_Contract is deprecated and will be removed in the next major release. Use Protocol\Transaction\Contract instead', E_USER_DEPRECATED);

