<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.TXInput</code>
 */
class TXInput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protocol.TXInput.raw raw_data = 1;</code>
     */
    protected $raw_data = null;
    /**
     * Generated from protobuf field <code>bytes signature = 4;</code>
     */
    protected $signature = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Protocol\TXInput\raw $raw_data
     *     @type string $signature
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Tron::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protocol.TXInput.raw raw_data = 1;</code>
     * @return \Protocol\TXInput\raw
     */
    public function getRawData()
    {
        return isset($this->raw_data) ? $this->raw_data : null;
    }

    public function hasRawData()
    {
        return isset($this->raw_data);
    }

    public function clearRawData()
    {
        unset($this->raw_data);
    }

    /**
     * Generated from protobuf field <code>.protocol.TXInput.raw raw_data = 1;</code>
     * @param \Protocol\TXInput\raw $var
     * @return $this
     */
    public function setRawData($var)
    {
        GPBUtil::checkMessage($var, \Protocol\TXInput\raw::class);
        $this->raw_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes signature = 4;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Generated from protobuf field <code>bytes signature = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature = $var;

        return $this;
    }

}

