<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.TXOutput</code>
 */
class TXOutput extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 value = 1;</code>
     */
    protected $value = 0;
    /**
     * Generated from protobuf field <code>bytes pubKeyHash = 2;</code>
     */
    protected $pubKeyHash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $value
     *     @type string $pubKeyHash
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Tron::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 value = 1;</code>
     * @return int|string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>int64 value = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes pubKeyHash = 2;</code>
     * @return string
     */
    public function getPubKeyHash()
    {
        return $this->pubKeyHash;
    }

    /**
     * Generated from protobuf field <code>bytes pubKeyHash = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPubKeyHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->pubKeyHash = $var;

        return $this;
    }

}

