<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * vote message
 *
 * Generated from protobuf message <code>protocol.Vote</code>
 */
class Vote extends \Google\Protobuf\Internal\Message
{
    /**
     * the super rep address
     *
     * Generated from protobuf field <code>bytes vote_address = 1;</code>
     */
    protected $vote_address = '';
    /**
     * the vote num to this super rep.
     *
     * Generated from protobuf field <code>int64 vote_count = 2;</code>
     */
    protected $vote_count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $vote_address
     *           the super rep address
     *     @type int|string $vote_count
     *           the vote num to this super rep.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Tron::initOnce();
        parent::__construct($data);
    }

    /**
     * the super rep address
     *
     * Generated from protobuf field <code>bytes vote_address = 1;</code>
     * @return string
     */
    public function getVoteAddress()
    {
        return $this->vote_address;
    }

    /**
     * the super rep address
     *
     * Generated from protobuf field <code>bytes vote_address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVoteAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->vote_address = $var;

        return $this;
    }

    /**
     * the vote num to this super rep.
     *
     * Generated from protobuf field <code>int64 vote_count = 2;</code>
     * @return int|string
     */
    public function getVoteCount()
    {
        return $this->vote_count;
    }

    /**
     * the vote num to this super rep.
     *
     * Generated from protobuf field <code>int64 vote_count = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVoteCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->vote_count = $var;

        return $this;
    }

}

