<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Vote Change
 *
 * Generated from protobuf message <code>protocol.Votes</code>
 */
class Votes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes address = 1;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>repeated .protocol.Vote old_votes = 2;</code>
     */
    private $old_votes;
    /**
     * Generated from protobuf field <code>repeated .protocol.Vote new_votes = 3;</code>
     */
    private $new_votes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address
     *     @type \Protocol\Vote[]|\Google\Protobuf\Internal\RepeatedField $old_votes
     *     @type \Protocol\Vote[]|\Google\Protobuf\Internal\RepeatedField $new_votes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Tron::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes address = 1;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>bytes address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.Vote old_votes = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOldVotes()
    {
        return $this->old_votes;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.Vote old_votes = 2;</code>
     * @param \Protocol\Vote[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOldVotes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protocol\Vote::class);
        $this->old_votes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.Vote new_votes = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNewVotes()
    {
        return $this->new_votes;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.Vote new_votes = 3;</code>
     * @param \Protocol\Vote[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNewVotes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protocol\Vote::class);
        $this->new_votes = $arr;

        return $this;
    }

}

