<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol\InternalTransaction;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.InternalTransaction.CallValueInfo</code>
 */
class CallValueInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * trx (TBD: or token) value
     *
     * Generated from protobuf field <code>int64 callValue = 1;</code>
     */
    protected $callValue = 0;
    /**
     * TBD: tokenName, trx should be empty
     *
     * Generated from protobuf field <code>string tokenId = 2;</code>
     */
    protected $tokenId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $callValue
     *           trx (TBD: or token) value
     *     @type string $tokenId
     *           TBD: tokenName, trx should be empty
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\Tron::initOnce();
        parent::__construct($data);
    }

    /**
     * trx (TBD: or token) value
     *
     * Generated from protobuf field <code>int64 callValue = 1;</code>
     * @return int|string
     */
    public function getCallValue()
    {
        return $this->callValue;
    }

    /**
     * trx (TBD: or token) value
     *
     * Generated from protobuf field <code>int64 callValue = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCallValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->callValue = $var;

        return $this;
    }

    /**
     * TBD: tokenName, trx should be empty
     *
     * Generated from protobuf field <code>string tokenId = 2;</code>
     * @return string
     */
    public function getTokenId()
    {
        return $this->tokenId;
    }

    /**
     * TBD: tokenName, trx should be empty
     *
     * Generated from protobuf field <code>string tokenId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTokenId($var)
    {
        GPBUtil::checkString($var, True);
        $this->tokenId = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(CallValueInfo::class, \Protocol\InternalTransaction_CallValueInfo::class);

