<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/Tron.proto

namespace Protocol\Inventory;

use UnexpectedValueException;

/**
 * Protobuf type <code>protocol.Inventory.InventoryType</code>
 */
class InventoryType
{
    /**
     * Generated from protobuf enum <code>TRX = 0;</code>
     */
    const TRX = 0;
    /**
     * Generated from protobuf enum <code>BLOCK = 1;</code>
     */
    const BLOCK = 1;

    private static $valueToName = [
        self::TRX => 'TRX',
        self::BLOCK => 'BLOCK',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(InventoryType::class, \Protocol\Inventory_InventoryType::class);

